careers/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from careers.views import Home, OfferDetail, ShowOfferList, OfferList, OfferSubmission, \
    ChangeOffer, ShowOfferPerDomain, ShowOfferPerLocation, ApplicationList, ChangeApplication, \
    ShowDomainList, DomainList, ChangeDomain, ShowLocationList, \
    LocationList, ChangeLocation, Thanks


urlpatterns = patterns(
    '',
    url(r'^$', Home.as_view(), name='home'),

    url(r'^offers/$', ShowOfferList.as_view(), name='show_offer_list'),
    url(r'^(?P<offer_slug>[-\w]+)$', OfferDetail.as_view(), name='offer_detail'),
    url(r'^offers/domain/(?P<domain_slug>[-\w]+)$', ShowOfferPerDomain.as_view(), name='show_offer_per_domain'),
    url(r'^offers/location/(?P<location_slug>[-\w]+)$', ShowOfferPerLocation.as_view(), name='show_offer_per_location'),

    url(r'^domains/$', ShowDomainList.as_view(), name='show_domain_list'),
    url(r'^locations/$', ShowLocationList.as_view(), name='show_location_list'),
    url(r'^(?P<offer_slug>[-\w]+)/apply$', login_required(OfferSubmission.as_view()), name='offer_submission'),
    url(r'^(?P<offer_slug>[-\w]+)/thanks$', login_required(Thanks.as_view()), name='thanks'),

    url(r'^locationList/$', permission_required('careers.ik_manage_offer')(LocationList.as_view()), name='location_list'),
    url(r'^changeLocation/$', permission_required('careers.ik_manage_offer')(ChangeLocation.as_view()), name='change_location'),
    url(r'^changeLocation/(?P<object_id>[-\w]+)$', permission_required('careers.ik_manage_offer')(ChangeLocation.as_view()),
        name='change_location'),

    url(r'^domainList/$', permission_required('careers.ik_manage_offer')(DomainList.as_view()), name='domain_list'),
    url(r'^changeDomain/$', permission_required('careers.ik_manage_offer')(ChangeDomain.as_view()), name='change_domain'),
    url(r'^changeDomain/(?P<object_id>[-\w]+)$', permission_required('careers.ik_manage_offer')(ChangeDomain.as_view()),
        name='change_domain'),

    url(r'^offerList/$', permission_required('careers.ik_manage_offer')(OfferList.as_view()), name='offer_list'),
    url(r'^changeOffer/$', permission_required('careers.ik_manage_offer')(ChangeOffer.as_view()), name='change_offer'),
    url(r'^changeOffer/(?P<object_id>[-\w]+)$', permission_required('careers.ik_manage_offer')(ChangeOffer.as_view()),
        name='change_offer'),

    url(r'^applicationList/$', permission_required('careers.ik_manage_application')(ApplicationList.as_view()),
        name='application_list'),
    url(r'^changeApplication/$', permission_required('careers.ik_manage_application')(ChangeApplication.as_view()),
        name='change_application'),
    url(r'^changeApplication/(?P<object_id>[-\w]+)/$', permission_required('careers.ik_manage_application')
    (ChangeApplication.as_view()), name='change_application'),
)

conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test, permission_required

from ikwen.core.views import Offline

from ikwen_kakocase.kakocase.views import AdminHome, MerchantList, Welcome, GuardPage, FirstTime
from ikwen_webnode.webnode.views import FlatPageView


from website.views import About, Webnode, Kakocase, Shavida, PinsView, Terms, Bundle, ServiceIndexes
from careers.views import Home

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^offline.html$', Offline.as_view(), name='offline'),
    url(r'^about$', About.as_view(), name='about'),
    url(r'^support_bundle$', Bundle.as_view(), name='support_bundle'),
    url(r'^terms$', Terms.as_view(), name='terms_and_conditions'),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^trade/', include('ikwen_kakocase.trade.urls', namespace='trade')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^marketing/', include('ikwen_kakocase.commarketing.urls', namespace='marketing')),
    url(r'^sales/', include('ikwen_kakocase.sales.urls', namespace='sales')),
    url(r'^shopping/', include('ikwen_kakocase.shopping.urls', namespace='shopping')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^serviceIndexes/(?P<start>[\d]+)/$', ServiceIndexes.as_view(), name='service_indexes'),
    url(r'^webnode/$', Webnode.as_view(), name='webnode'),
    url(r'^kakocase/$', Kakocase.as_view(), name='kakocase'),
    # url(r'^shavida/$', Shavida.as_view(), name='shavida'),
    url(r'^pinsview/$', PinsView.as_view(), name='pinsview'),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    # Foulassi URLs
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),

    url(r'^daraja/', include('daraja.urls', namespace='daraja')),
    url(r'^guardPage/$', GuardPage.as_view(), name='guard_page'),

    url(r'^$', Home.as_view(), name='home'),
    url(r'^', include('careers.urls', namespace='careers')),

)

careers/models.py
from django.db import models
from django.db.models import Model

from django.template.defaultfilters import slugify
from django.utils.translation import gettext as _, get_language
# from django.contrib.gis.utils import GeoIP

from ikwen.accesscontrol.models import Member
from ikwen.core.fields import FileField, FieldFile
from ikwen.core.models import Country


class Location(Model):
    UPLOAD_TO = 'careers/Locations'
    slug = models.SlugField(max_length=250, unique=True, null=True, blank=True)
    town = models.CharField(max_length=150)
    country = models.ForeignKey(Country)
    cover_image = models.ImageField(_('Cover image'),
                                    help_text=_('Upload a cover image which help to illustrates the location'),
                                    upload_to=UPLOAD_TO, null=True)

    def __unicode__(self):
        return "%s, %s" % (self.town, self.country)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.id:
            self.slug = slugify(self.__unicode__())
        super(Location, self).save()


class Domain(Model):
    UPLOAD_TO = 'careers/Domains'
    slug = models.SlugField(max_length=250, unique=True, null=True, blank=True)
    name = models.CharField(max_length=100)
    cover_image = models.ImageField(_('Cover image'),
                                    help_text=_('Upload a cover image which help to illustrates the domain'), upload_to=UPLOAD_TO)
    short_description = models.TextField(_("Small description"), blank=True, null=True)
    target = models.CharField(_("Target reason"), max_length=100, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.id:
            self.slug = slugify(self.name)
        super(Domain, self).save()


class Offer(Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True, null=True, blank=True)
    description = models.TextField()
    position_count = models.IntegerField(default=1)
    domain = models.ForeignKey(Domain)
    location = models.ForeignKey(Location)

    def __unicode__(self):
        return self.slug
    
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.id:
            self.slug = slugify(self.name)
        super(Offer, self).save()


class Application(Model):
    upload_to = 'careers/Applications'
    member = models.ForeignKey(Member, null=True)
    offer = models.ForeignKey(Offer, help_text=_('Position to which you apply'))
    allowed_notifications = models.BooleanField(help_text=_('Does applicant which '
                                                           'to be notified for future job opportunities'),
                                               default=False, editable=True, null=True, blank=True)
    resume = FileField(verbose_name=_('Resume or CV'), allowed_extensions=['pdf', 'doc'],
                       upload_to=upload_to, help_text=_('Upload your resume or CV here'))
    current_company = models.CharField(_('Name of the current company'), max_length=100,
                                       help_text=_('Name of the company you are currently working in'), null=True, blank=True)

    linkedin_url = models.URLField(_('LinkedIn URL'), null=True, blank=True)
    github_url = models.URLField(_('Github URL'), null=True, blank=True)
    portfolio_url = models.URLField(_('Link to your Portfolio'), null=True, blank=True)
    other_website = models.URLField(_('Other website URL'), null=True, blank=True)

    facebook_url = models.URLField(_('Facebook URL'), null=True, blank=True)
    instagram_url = models.URLField(_('Instagram URL'), null=True, blank=True)
    twitter_url = models.URLField(_('Twitter URL'), null=True, blank=True)
    youtube_url = models.URLField(_('YouTube URL'), null=True, blank=True)

    additional_information = models.TextField(_('Additional information'), null=True, blank=True,
                                              help_text=_('Add cover letter or anything else you want to share'))
    location = models.ForeignKey(_('Location'),
                                 help_text=_('Put the correct area and city where you live separated by a comma'),
                                 blank=True, null=True)

    def __unicode__(self):
        return "%(applicant_name)s: %(offer)s" %\
               {'applicant_name': self.member.first_name, 'offer': self.offer}
    # g = GeoIP()
    # ip = request.META.get('REMOTE_ADDR', None)
    # if ip:
    #     city = g.city(ip)['city']
    # else:
    #     city = 'Rome'  # default city

careers/templates/careers/home.html
{% extends 'website/base.html' %}
{% load i18n humanize static auth_tokens  %}

{% block page_title %}
    <title>{% blocktrans with company_name=config.company_name %}Careers at ikwen {% endblocktrans %} </title>
{% endblock %}

{% block page_content %}
    <div class="home">
        {% block banner %}
            <section>
                 <div id="banner-top">
                    <div class="section-banner-top" style="background-image: url({% static 'careers/img/ikwen_dev_office.jpg' %});">
                        <div class="section-banner-inner">
                            <div class="col-md-6 col-sm-6 col-md-offset-3 col-sm-offset-3 text-center">
                                <h1>{% trans 'Jobs' %}</h1>
                                <p>{% trans 'Turn your multiple skills into a valuable innovative IT projects at ikwen' %}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </section>
        {% endblock %}
        <div class="clearfix"></div>
        {% if offer_list %}
            <section class="offer-list">
                <div class="container inner">
                    {% block customize_body %}{% endblock %}
                        <div class="headers hidden-xs">
                            <div class="col-sm-7">{% trans 'JOB' %}</div>
                            <div class="col-sm-4">{% trans 'DOMAIN' %}</div>
                            <div class="col-sm-1">{% trans 'POSITIONS' %}</div>
                            <div class="clearfix"></div>
                        </div>
                    {% for offer in offer_list %}
                        <div class="offer">
                            <a href="{% url 'careers:offer_detail' offer.slug %}" class="col-sm-7 h2">{{ offer.name }}</a>
                            <p class="col-sm-4 h3">{{ offer.domain }}</p>
                            <p class="col-sm-1 h3">{{ offer.position_count }}</p>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                    {% endfor %}
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </section>
        {% endif %}
        <div class="clearfix"></div>
        <section>
            <div class="container">
                <h1 class="text-center title">{% trans '...speaking of jobs' %}</h1>
                <div class="bottom-side text-center">
                    <a class="col-sm-4" href="https://ikwen.com/about#section-values">
                        <div class="image" style="background-image: url({% static 'careers/img/our-values1.jpg' %});"></div>
                        <h2>{% trans 'Our values' %}</h2>
                        <p class="text-muted">{% trans 'Get to know the philosophy that makes our determination' %}</p>
    {#                    <p><span class="blurb-item--meta icon-arrow-right blurb-item--meta-content">{% trans 'READ MORE' %} </span></p>#}
                        <p>{% trans 'READ MORE' %}<i class="fas fa-long-arrow-alt-right animated infinite slideInLeft"></i></p>
                    </a>
                    <a class="col-sm-4" href="{% url 'careers:show_domain_list' %}">
                        <div class="image" style="background-image: url({% static 'careers/img/job-categories.jpg' %});"></div>
                        <h2>{% trans 'Our job categories' %}</h2>
                        <p class="text-muted">{% trans 'What are you passionate in ?' %}</p>
    {#                    <p><span class="blurb-item--meta icon-arrow-right blurb-item--meta-content">{% trans 'READ MORE' %} </span></p>#}
                        <p>{% trans 'READ MORE' %}<i class="fas fa-long-arrow-alt-right animated infinite slideInLeft"></i></p>
                    </a>
                    <a class="col-sm-4" href="{% url 'careers:show_location_list' %}">
                        <div class="image" style="background: url({% static 'careers/img/our-locations.png' %});"></div>
                        <h2>{% trans 'Locations' %}</h2>
                        <p class="text-muted">{% trans 'Find out how global we are' %}</p>
    {#                    <p><span class="blurb-item--meta icon-arrow-right blurb-item--meta-content">{% trans 'READ MORE' %} </span></p>#}
                        <p>{% trans 'READ MORE' %}<i class="fas fa-long-arrow-alt-right animated infinite slideInLeft"></i></p>
                    </a>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

careers/templates/careers/offer_detail.html
{% extends 'website/base.html' %}
{% load i18n humanize static auth_tokens  %}

{% block meta %}
    {{ block.super }}
    <meta property="og:title" content="{% blocktrans with offer_name=offer.name company_name=config.company_name %}{{ offer_name }} - Careers at ikwen {% endblocktrans %}" />
{% endblock %}

{% block page_title %}
    <title>{% blocktrans with offer_name=offer.name company_name=config.company_name %}
        {{ offer_name }} - Careers at ikwen
    {% endblocktrans %}</title>
{% endblock %}

{% block head_style %}
    {{ block.super }}
    <style>
        body {background-color: #fff}
        section.offer-detail {background-color: #fff; padding-top: 15vh; padding-bottom: 15vh;}
        section.offer-detail .actions .product-social-share {color: #fff; width: 100%!important;}
        section.offer-detail .actions .share {margin: 20px auto;}
        section.offer-detail .apply {width: auto; height: 50px; line-height: 35px; display: block; margin-top: 40px}
        section.offer-detail .apply i {font-size: 18px; color: #fff}
        section.offer-detail .detail {margin-top: 50px}
        section.offer-detail h1 {font-weight: 900; color: #191414; font-size: 60px}
        section.offer-detail p {color: #263b82;}

        .fb-share-button {margin-top: -8px; padding: 0}
        .icon-linkedin.share-link {height: 22px; width: 80px; margin-top: 3px; line-height: 11px;
            padding-top: 3px; padding-bottom: 3px; background: #0C77B5; color: #fff;}
        .twitter-share-button {margin: 0 10px}
        .social-icon {display: -webkit-inline-box;}
        footer {margin: 0; padding: 30px}

        @media (max-width: 767px){
            .single-right h4 {font-size: 1.8em;margin-top: 10px;margin-bottom: 5px}
            #bottom-tabs li {text-align: center;width: 50%;}
            .bottom-cntr > form {float: left;margin-left: 40px;}
            .bottom-cntr i {color: #FFF; font-size: 15px}
            #cd-search1 .cd-search input {padding: .1em .5em;}
            .header-xs h3.app-name a {width: 300%; float: left}
            .social-icon {margin-top: 1.8em; padding-left: 15px;}
            .social-icon a i {font-size: 35px}
        }
        /* Small devices (tablets, 768px and up) */
        @media (min-width: 768px) {
            .new-grid h5 {font-size: 1.5em;}
            .new-grid h6 {font-weight: 600; margin: 1em 0;font-size: 1.2em;}
            .new-grid span {font-size: 0.96em;}
            .modal .product-about .product-price em {color: #ff0000}
            .single-right h4 {margin-bottom: .2em}
            .social-icon {margin-top: 1.8em; padding-left: 15px;}
        }

        /* Medium devices (desktops, 992px and up) */
        @media (min-width: 992px) {
            .single-right h4 {margin-bottom: .2em}
            .social-icon {float: left; margin-top: 0;padding-left: 0; margin-bottom: 0}
        }

        /* Large devices (large desktops, 1200px and up) */
        @media (min-width:1200px) {
        }
        .reveal {visibility: visible; opacity: 1; display: block}
        @media (max-width: 767px) {
            section.offer-detail h1 {font-size: 30px}
            section .actions {margin-top: 40px}
            section.offer-detail .apply {font-weight: 600; font-size: 20px; padding: 10px 40px; height: 50px;  margin: 40px 0;width: auto; line-height: 27px; display: block;}
        }

    </style>
{% endblock %}
{% block header %}
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <script>window.twttr = (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
        t = window.twttr || {};
      if (d.getElementById(id)) return t;
      js = d.createElement(s);
      js.id = id;
      js.src = "https://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js, fjs);

      t._e = [];
      t.ready = function(f) {
        t._e.push(f);
      };

      return t;
    }(document, "script", "twitter-wjs"));</script>
    {{ block.super }}
{% endblock %}

{% block page_content %}
    {% url 'careers:offer_detail' offer.slug as current_url %}
    <section class="offer-detail">
        <div class="container">
            <h1 class="h1">{{ offer.name }}</h1>
            <p class="text-muted">{{ offer.domain }} in {{ offer.location }}</p>
            <div class="clearfix"></div>
            <div class="detail">
                <div class="col-sm-8">
                    {{ offer.description|safe }}
                </div>
                <div class="col-sm-offset-1 col-sm-3 actions">
                    <h4 class="share text-center" ><i class="fa fa-share-alt"></i> {% trans 'SHARE' %}</h4>
                    <div class="social-icon hidden-xs">
                        <div class="fb-share-button btn" data-href="{{ service.url }}{{ current_url }}" data-layout="button" data-mobile-iframe="true">
                            <a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php">{% trans "Share" %}</a>
                        </div>
                        <a class="twitter-share-button btn" href="https://twitter.com/intent/tweet?url={{ service.url }}{{ current_url }}" data-size="small">Tweet</a>
                        <a class="icon-linkedin share-link btn btn-sm" href="http://www.linkedin.com/shareArticle?mini=true&amp;url={{ service.url }}{{ current_url }}" title="Share on LinkedIn" target="_blank" rel="noopener noreferrer"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="row visible-xs">
                        <div class="col-sm-offset-2 col-sm-4 col-xs-4" data-href="{{ service.url }}{{ current_url }}" data-layout="button" data-mobile-iframe="true">
                            <a class="product-social-share btn btn-block" target="_blank"  href="https://www.facebook.com/sharer/sharer.php?u={{ service.url }}{{ current_url }}"  style="background: #3b5998;">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </div>
                        <div class="col-sm-4 col-xs-4">
                            <a class="product-social-share btn btn-block" data-toggle="modal" data-target="#twitter-share" href="https://twitter.com/intent/tweet?url={{ service.url }}{{ current_url }}" style="background: #1da1f2;">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </div>
                        <div class="col-xs-4">
                            <button class="product-social-share whatsapp-share btn btn-block" data-toggle="modal" data-target="#whatsapp-share" style="background: #25d366;">
                                <i class="fab fa-whatsapp"></i>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
    {#                </div>#}
                    <a href="{% url 'careers:offer_submission' offer.slug %}" class="btn btn-sm btn-deep-blue apply"><i class="fas fa-external-link-alt"></i> {% trans 'APPLY NOW' %}</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        {% url 'careers:offer_detail' offer.slug as current_url %}
        $('body').on('click', '.whatsapp-share', () => {
            let url = "{{ service.url }}{{ current_url }}";
            window.location = 'https://api.whatsapp.com/send?text=' + url;
        });
    </script>
{% endblock %}

careers/templates/careers/offer_submission.html
{% extends 'website/base.html' %}
{% load i18n humanize static auth_tokens  %}

{% block meta %}
    {{ block.super }}
    <meta property="og:title" content="{% blocktrans with offer_name=offer.name company_name=config.company_name %}{{ offer_name }} - Careers at ikwen {% endblocktrans %}" />
{% endblock %}

{% block page_title %}
    <title>{% blocktrans with offer_name=offer.name company_name=config.company_name %}
        {{ offer_name }} - Careers at ikwen {% endblocktrans %}</title>
{% endblock %}

{% block head_style %}
    {{ block.super }}
    <link href="{% static 'ikwen/css/uploader-single.css' %}?v=20.8.17" media="screen" rel="stylesheet" type="text/css" />
    <style>
        body section:first-of-type:not(.photos) {padding-top: 15vh; padding-bottom: 9vh}
        section .apply {width: auto; height: 50px; line-height: 35px; display: block; margin-top: 40px}
        section .apply i {font-size: 18px}
        section .detail {margin-top: 50px}
        section form h4 {margin: 40px auto; font-weight: 700}
    </style>
{% endblock %}

{% block head_js %}
    <script src="{% static 'ikwen/js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'ikwen/ajaxuploader/js/fileuploader.js' %}"></script>
{% endblock %}

{%  block page_content %}
    {% block head %}
        <section style="background: #fff" >
            <div class="container">
                <div class="col-sm-6" style="margin: auto; float: none">
                    <h2>{{ offer.name }}</h2>
                    <h4 class="text-muted">{{ offer.location }} / {{ offer.domain }}</h4>
                </div>
            </div>
        </section>
    {% endblock %}
    {% block submission %}
        <section style="background: #f9f9f9">
            {% if errors %}<p class="alert alert-danger">{{ errors }}</p>{% endif %}
            <div class="container">
                <div class="col-sm-6" style="margin: auto; float: none">
                    <span class="warning warning-alerts resume-required tpl" style="color: red">{% trans 'Your resume is required...' %}</span>
                    <form id="application" method="post">{% csrf_token %}
                        <h4>{% trans 'SUBMIT YOUR APPLICATION' %}</h4>
                        <input type="hidden" name="offer" value="{{ offer.id }}">
                        <input type="hidden" name="member" value="{{ user.id }}">
                        <input type="hidden" name="label_field" value="name">
                        <input type="hidden" name="slug_field" value="slug">
                        {% for media_obj in media_field_list %}
                            <div class="form-group" style="padding-left: 0; margin-right: 15px">
                                <div>
                                {% with media=media_obj %}
                                    {% include 'core/snippets/media_uploader_single.html' %}
                                {% endwith %}
                                </div>
                            </div>
                            <p class="help clear">
                                {% if media.media.name and not media.media.field.read_only %}
                                <i class="glyphicon glyphicon-trash delete-media delete-media{{ media.counter }}" title="{% trans "Delete media" %}"></i>
                                <span>{{ media.media.field.help_text|safe }}</span>
                                {% else %}
                                <span>{{ media.media.field.help_text|safe }}</span>
                                {% endif %}
                            </p>
                        {% endfor %}
                        <div class="form-group">
                            <label for="id_current-company">{% trans 'Current company' %}</label>
                            <input type="text" id="id_current_company" name="current_company" class="form-control input-sm">
                        </div>
                        <div class="form-group">
                            <label for="id_location">{% trans 'Location' %}</label>
                            <select class="form-control" name="location" id="id_location">
                                {% for location in location_list %}
                                    <option value="{{ location.id }}">{{ location }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <h4>{% trans 'Professional Links' %}</h4>
                        <div class="form-group">
                            <label for="id_linkedin_url">{% trans 'LinkedIn URL' %}</label>
                            <input type="url" id="id_linkedin_url" name="linkedin_url" class="form-control input-sm">
                        </div>
                        <div class="form-group">
                            <label for="id_github_url">{% trans 'Github URL' %}</label>
                            <input type="url" id="id_github_url" name="github_url" class="form-control input-sm">
                        </div>
                        <div class="form-group">
                            <label for="id_portfolio_url">{% trans 'Portfolio URL' %}</label>
                            <input type="url" id="id_portfolio_url" name="portfolio_url" class="form-control input-sm">
                        </div>
                        <div class="form-group">
                            <label for="id_other-website">{% trans 'Other Website' %}</label>
                            <input type="text" id="id_other_website" name="other_website" class="form-control input-sm">
                        </div>
                        <h4>{% trans 'Social Links' %}</h4>
                        <div class="form-group">
                            <label for="id_facebook_url">{% trans 'Facebook URL' %}</label>
                            <input type="url" id="id_facebook_url" name="facebook_url" class="form-control input-sm">
                        </div>
                        <div class="form-group">
                            <label for="id_twitter_url">{% trans 'Twitter URL' %}</label>
                            <input type="url" id="id_twitter_url" name="twitter_url" class="form-control input-sm">
                        </div>
                        <div class="form-group">
                            <label for="id_instagram_url">{% trans 'Instagram URL' %}</label>
                            <input type="url" id="id_instagram_url" name="instagram_url" class="form-control input-sm">
                        </div>
                        <div class="form-group">
                            <label for="id_youtube_url">{% trans 'YouTube URL' %}</label>
                            <input type="url" id="id_youtube_url" name="youtube_url" class="form-control input-sm">
                        </div>
                        <h4>{% trans 'ADDITIONAL INFORMATION' %}</h4>
                        <textarea class="form-control input-sm" id="id_additional_information" name="additional_information" placeholder="{% trans 'Add cover letter or anything else you want to share' %}" style="height: 250px"></textarea>
                        <div class="checkbox" style="border-top: solid 1px #efefee; margin-top: 20px; padding: 15px 0">
                            <label>
                                <input type="checkbox" id="id_allowed_notifications" name="allowed_notifications">{% blocktrans %}Yes, <strong>ikwen</strong> can contact me about future job opportunities {% endblocktrans %}
                            </label>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6" style="margin: auto; float: none">
                               <button class="btn btn-sm btn-deep-blue btn-block submit">{% trans 'Submit' %}</button>
                            </div>
                        </div>
                        <span class="warning warning-alerts submission-failed tpl" style="color: red">{% trans 'Failed to submit your application ...' %}</span>
                    </form>
                </div>
            </div>
        </section>
    {% endblock %}

{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        (() => {
          $('form#application').submit(() => {
             if ($("[name='resume']").val() === '{% get_media_prefix %}'){
                 $('.resume-required, .submission-failed').show();
                 return false;
             }
          });
        })()
    </script>
{% endblock %}