conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test, permission_required

from ikwen.core.views import Offline

from ikwen_kakocase.kakocase.views import AdminHome, MerchantList, Welcome, GuardPage, FirstTime
from ikwen_webnode.webnode.views import FlatPageView


from website.views import About, Webnode, Kakocase, Shavida, PinsView, Terms, Bundle, ServiceIndexes
from careers.views import Home

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^offline.html$', Offline.as_view(), name='offline'),
    url(r'^about$', About.as_view(), name='about'),
    url(r'^support_bundle$', Bundle.as_view(), name='support_bundle'),
    url(r'^terms$', Terms.as_view(), name='terms_and_conditions'),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^trade/', include('ikwen_kakocase.trade.urls', namespace='trade')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^marketing/', include('ikwen_kakocase.commarketing.urls', namespace='marketing')),
    url(r'^sales/', include('ikwen_kakocase.sales.urls', namespace='sales')),
    url(r'^shopping/', include('ikwen_kakocase.shopping.urls', namespace='shopping')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^serviceIndexes/(?P<start>[\d]+)/$', ServiceIndexes.as_view(), name='service_indexes'),
    url(r'^webnode/$', Webnode.as_view(), name='webnode'),
    url(r'^kakocase/$', Kakocase.as_view(), name='kakocase'),
    # url(r'^shavida/$', Shavida.as_view(), name='shavida'),
    url(r'^pinsview/$', PinsView.as_view(), name='pinsview'),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    # Foulassi URLs
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),

    url(r'^daraja/', include('daraja.urls', namespace='daraja')),
    url(r'^guardPage/$', GuardPage.as_view(), name='guard_page'),

    url(r'^$', Home.as_view(), name='home'),
    url(r'^', include('careers.urls', namespace='careers')),

)

templates/website/snippets/edge_panel.html
{% load i18n humanize staticfiles cache auth_tokens %}
<div class="edge-panel-left-container visible-xs">
    <div id="side-nav" class="edge-panel-left subtle-shade" style="margin-left: -300px">
        <div class="wrapper">
            <div class="stage">
                <div class="top-edge-panel" style>
                    <div class="panel-top">
                    <img src="{% static 'website/img/Logo-ikwen_780x780.png' %}" class="img-responsive text-center" style="margin:auto; width: 60%">
                </div>
                <div class="divider"></div>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
                        <li class="dropdown">
                          <a href="javascript:;" data-toggle="collapse" data-target="#daraja-version" aria-expanded="false">Daraja <b class="caret"></b> </a>
                          <ul id="daraja-version" class="collapse" style="list-style: none">
                            <li role="presentation" style="height: 42px; padding: 10px 0">
                                <a href="https://ikwen.com{% url 'daraja:home' %}">{% trans "Community" %}</a>
                            </li>
                            <li role="presentation" style="height: 42px; padding: 10px 0">
                                <a href="https://ikwen.com{% url 'daraja:for_businesses' %}">{% trans "Enterprise" %}</a>
                            </li>
                          </ul>
                        </li>
{#                        <li><a href="{% url 'daraja:home' %}"> Daraja</a></li>#}
                        <li class="tsunami"><a href="https://www.ikwen.com/tsunami/"> Tsunami</a></li>
                        <li class="dropdown">
                          <a href="javascript:;" data-toggle="collapse" data-target="#foulassi-version" aria-expanded="false">Foulassi <b class="caret"></b> </a>
                          <ul id="foulassi-version" class="collapse" style="list-style: none">
                            <li role="presentation" style="height: 42px; padding: 10px 0">
                                <a href="https://ikwen.com{% url 'foulassi:home' %}">{% trans "Parent" %}</a>
                            </li>
                            <li role="presentation" style="height: 42px; padding: 10px 0">
                                <a href="https://ikwen.com{% url 'foulassi:home_saas' %}">{% trans "School" %}</a>
                            </li>
                          </ul>
                        </li>
{#                        <li><a href="{% url 'foulassi:home' %}"> Foulassi</a></li>#}
                        <li><a href="https://ikwen.com{% url 'kakocase' %}"> Kakocase</a></li>
                        <li><a href="https://ikwen.com{% url 'pinsview' %}"> PinsView</a></li>
{#                        <li class="kakocase"><a href="{% url 'ikwen:company_profile' 'webnode' %}"> Webnode</a></li>#}
{#                        <li class="kakocase"><a href="{% url 'ikwen:company_profile' 'shavida' %}"> Shavida</a></li>#}
                        <div class="divider"></div>
                        <li><a href="http://blog.ikwen.com">{% trans 'Blog' %}</a> </li>
                        <li><a href="http://support.ikwen.com">{% trans 'Support' %}</a> </li>
                        <li><a href="{% url 'about' %}">{% trans 'About' %}</a> </li>
                        <li><a href="{% url 'terms_and_conditions' %}">{% trans 'Terms & conditions' %}</a> </li>
                        {% if agreement_page %}
{#                            <li><a href="{% url 'flatpage' agreement_page.url %}">{{ agreement_page.title }}</a></li>#}
                        {% endif %}
                    </ul>
                    <div class="clearfix"></div>

                    <div class="social-icon">
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://www.linkedin.com/company/18357139/"target="_blank" class="ico ico-linkedin"><i class="fab fa-linkedin-in"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://twitter.com/ikwenSARL"target="_blank" class="ico ico-twitter"><i class="fab fa-twitter"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://www.facebook.com/Ikwen.SARL" target="_blank" class="ico ico-facebook"><i class="fab fa-facebook"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://www.youtube.com/channel/UCzhHrosFOA6RC2H9MqR9jxA"target="_blank" class="ico ico-youtube"><i class="fab fa-youtube"></i></a>
                        {% include 'core/snippets/language_switcher.html' %}
                    </div>
                </div>
            </div>

            <div id="footer" class="text-muted">
                &copy; {{ year }} <a class="company-name" href="{{ service.url }}"><strong>{{ config.company_name }}</strong></a>.
                {% trans "All rights reserved." %}
                {% if config.legal_mentions_url %}
                - <a href="{{ config.legal_mentions_url }}" style="color: #666; text-decoration: none">{% trans "Legal mentions" %}</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>